.TH DTUTILS 3 "" "" "Darktable dtutils functions"
.SH NAME
dtutils
.SH SYNOPSIS
A Darktable lua utilities library
.SH USAGE
local du = require "lib/dtutils"
.SH DESCRIPTION
dtutils provides a common library of functions used to build
    lua scripts. There are also sublibraries that provide more functions.
.SH RETURN VALUE
du - library - the library of functions
.SH SEE ALSO
dtutils.debug(3), dtutils.file(3), dtutils.log(3), dtutils.string(3)
.SH LICENSE
This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
.SH COPYRIGHT
Copyright (C) 2016 Bill Ferguson <wpferguson@gmail.com>.
    Copyright (C) 2016 Tobias Jakobs
