.TH PREQUIRE 3 "" "" "Darktable dtutils functions"
.SH NAME
prequire
.SH SYNOPSIS
a protected lua require
.SH USAGE
local du = require "lib/dtutils"

    local status, lib = du.prequire(req_name)
      req_name - the filename of the lua code to load without the ".lua" filetype
.SH DESCRIPTION
prequire is a protected require that can survive an error in the code being loaded without
    bringing down the calling routine.
.SH RETURN VALUE
status - boolean - true on success
    lib - if status is true, then the code, otherwise an error message
.SH EXAMPLE
local status, lib = prequire("lib/dtutils.file") which would load lib/dtutils/file.lua which 
    would return a status of true and the reference to the library in lib.
